apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
      - ./infrs/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: janna/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: janna/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .